name: Terraform Security Check with Checkov

on:
  push:
    branches:
      - main
    paths:
      - 'checkov/**'
  pull_request:
    branches:
      - main
  workflow_dispatch: # Evento que aciona o fluxo de trabalho manualmente
    inputs: # Define os inputs do fluxo de trabalho
      name: # Define o input "name"
        description: 'Trigger manual do Workflow' # Descrição do input

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Checkov
        run: |
          pip install checkov
      
      - name: Run Checkov
        run: |
          checkov -d /checkov --quiet --output json --output-file checkov-report.json
      
      - name: Upload Checkov Report
        uses: actions/upload-artifact@v2
        with:
          name: checkov-report
          path: checkov/checkov-report.json
