name: Secrets Check with Trufflehog
on:
  push:
    branches:
      - main  # Aciona o fluxo de trabalho quando houver push na brach main
  pull_request:
    branches:
      - main # Aciona o fluxo de trabalho quando houver PR na brach main
  workflow_dispatch:  # Aciona manualmente o fluxo de trabalho
    inputs:  # Define entradas para o fluxo de trabalho
      name:  # Define a entrada "name"
        description: 'Acionador manual do fluxo de trabalho'  # Descrição da entrada

jobs:
  snyk-scan:
    name: Trufflehog Security Check # Nome do trabalho
    runs-on: ubuntu-latest # Sistema operacional em que o trabalho será executado (no caso, Ubuntu)
    steps: # Passos a serem executados no trabalho

      - name: Run Trufflehog
        run: docker run --rm -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --repo https://github.com/toolbox-playground/pipelines-seguranca-exemplo-basico # Roda o Trufflehog a partigar da imagem Docker
